kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-temperature-sequence
  version: '1.0'
  namespace: singapore-temperature-api
  description: Policy sequence for the Singapore Temperature API
  tags:
    - environment
    - temperature
spec:
  monitoring:
    $ref: singapore-temperature-api:singapore-temperature-telemetry:1.0
  main:
    - $ref: singapore-temperature-api:singapore-temperature-extract-identity:1.0
    - $ref: singapore-temperature-api:singapore-temperature-authenticate:1.0
    - $ref: singapore-temperature-api:singapore-temperature-authorize:1.0
    - $ref: singapore-temperature-api:singapore-temperature-invoke:1.0
  error: []
  finally: []
