kind: URISchemes
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-temperature-uri-schemes
  version: '1.0'
  namespace: singapore-temperature-api
  description: URI schemes for the Singapore Temperature API
  tags:
    - environment
    - temperature
spec:
  uriSchemes:
    - https
