kind: Authorize
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-temperature-authorize
  version: '1.0'
  namespace: singapore-temperature-api
  description: Authorizes the caller against a registered subscription
  tags:
    - environment
    - temperature
spec:
  operation:
    subscription: {}
