kind: Authenticate
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-temperature-authenticate
  version: '1.0'
  namespace: singapore-temperature-api
  description: Authenticates the API Key against a registered subscription
  tags:
    - environment
    - temperature
spec:
  operation:
    subscription: {}
