kind: ExtractIdentity
apiVersion: api.ibm.com/v1
metadata:
  name: singapore-temperature-extract-identity
  version: '1.0'
  namespace: singapore-temperature-api
  description: Extracts API Key credentials (clientId + clientSecret) from request headers
  tags:
    - environment
    - temperature
spec:
  credentialType:
    apiKey:
      clientId:
        httpHeader:
          name: X-IBM-Client-Id
      clientSecret:
        httpHeader:
          name: X-IBM-Client-Secret
